package org.bookingplatform.constant;

public enum NotificationType {
    BOOKING_CREATED, BOOKING_CONFIRMED, BOOKING_CANCELLED, REVIEW_RECEIVED,
    PROFILE_APPROVED, PROFILE_REJECTED, PAYMENT_RECEIVED, REMINDER
}